version: '2.1'
#version: '3'
#Test1

services:

  demo-db:
    image: containertema1orsantudor30641.azurecr.io/db
    restart: always
    environment:
      MYSQL_DATABASE: 'city-db'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'Ciocoflender66-'
      #MYSQL_ROOT_PASSWORD: 'Ciocoflender66-'
    healthcheck:
      #test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root"]
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      #test: ["CMD", "mysqladmin", "-u$MYSQL_USER", "-p$MYSQL_PASSWORD",  "ping", "-h", "localhost"]
      timeout: 45s #120s #45s
      interval: 10s #100s #10s
      retries: 5
    ports:
      - "3306:3306"
    container_name: demo-db #city-db

  demo-be:
    image: containertema1orsantudor30641.azurecr.io/orsantudor30641backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      # - DB_IP=172.22.0.2
      # - DB_IP=city-db
      # - DB_IP=172.22.0.2
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=Ciocoflender66-
      - DB_DBNAME=city-db
    #depends_on:
    #  demo-db:
    #    condition: service_healthy